language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py develop
  - pip install --use-mirrors argparse coverage flake8 nose requests
script:
  - nosetests --with-coverage --cover-branches --cover-package=vecc
  - flake8 vecc
