language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install --use-mirrors argparse coverage flake8 requests
  - python setup.py develop
script:
  - python -m unittest
  - flake8 mailbot
